version: '3.8'

services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: a03_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: a03_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro,z
    networks:
      - a03_network

  app:
    platform: linux/amd64
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: a03_php_fpm
    restart: always
    volumes:
      - ./src:/var/www/html:z
    depends_on:
      - db
    networks:
      - a03_network

  webserver:
    platform: linux/amd64
    image: httpd:2.4
    container_name: a03_apache
    restart: always
    ports:
      - "8083:80"
    volumes:
      - ./src:/var/www/html:z
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro,z
    depends_on:
      - app
      - db
    networks:
      - a03_network

networks:
  a03_network:
    driver: bridge